name: Continuous Integration

on:
  push:
    branches: [ main ]       
  pull_request:
    branches: [ main ]       
  workflow_dispatch: {}       

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Java 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build & Test (Maven)
        run: mvn -B -ntp clean verify

      - name: List build outputs (debug)
        if: always()
        run: |
          pwd
          ls -la
          find . -type f \( -name "*.jar" -o -name "*.war" \) -print

      - name: Upload Maven artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            **/target/*.jar
            **/target/*.war
          if-no-files-found: warn
