name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Temurin 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build & Test
        run: mvn -B -ntp clean verify

      - name: List build outputs (debug)
        run: |
          pwd
          ls -la
          find . -type f \( -name "*.jar" -o -name "*.war" \) -print

      - name: Publicar artefatos Maven
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            **/target/*.jar
            **/target/*.war
			
