name: Continuous Delivery

on:
  push:
    branches: [ main ]             

jobs:
  deliver:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
  