name: Continuous Delivery

on:
  push:
    branches: [ main ] 

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Java 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build the project and create the .war file
        run: mvn clean package -DskipTests

      - name: Upload build artifact to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: app-war
          path: target/*.war
